export const checkedAt = '12 set. 2026';

export const sources = [
  {id:'prograd-monitoria', name:'Programa de Monitoria', organ:'PROGRAD / UFBA', url:'https://prograd.ufba.br/programa-de-monitoria', content:'Editais de monitoria com bolsa, voluntária e cursos de férias.', format:'Página temática + PDFs de editais', cadence:'Atualização por edital/semestre; a página apresenta editais vigentes e finalizados.', editals:true, feed:'Não encontrado na verificação inicial.', monitoring:'semiestruturada', automation:'Possível detectar novos links/títulos na página; leitura do PDF e validação humana são necessárias.', reliability:'Oficial primária', verified:checkedAt},
  {id:'proae', name:'Inscrições abertas / notícias', organ:'PROAE / UFBA', url:'https://proae.ufba.br/pt-br/inscricoes-abertas', content:'Assistência estudantil, benefícios, auxílios e bolsas.', format:'Página de notícias e páginas de edital', cadence:'Frequente, conforme notícias datadas na página inicial.', editals:false, feed:'Não encontrado na verificação inicial.', monitoring:'semiestruturada', automation:'Possível monitorar listagem de notícias; status e anexos exigem conferência humana.', reliability:'Oficial primária', verified:checkedAt},
  {id:'proext', name:'Editais', organ:'PROEXT-AC / UFBA', url:'https://proext.ufba.br/tags/edital', content:'Editais e resultados de extensão, arte, cultura e ACCS.', format:'Tag/listagem de notícias, páginas e anexos.', cadence:'Atualização por chamadas, resultados e retificações.', editals:true, feed:'Não encontrado na verificação inicial.', monitoring:'semiestruturada', automation:'Monitoramento da página é viável; cronogramas e retificações devem ser revisados por pessoa.', reliability:'Oficial primária', verified:checkedAt},
  {id:'sri', name:'Editais', organ:'Superintendência de Relações Internacionais / UFBA', url:'https://sri.ufba.br/pt-br/editais', content:'Intercâmbio, mobilidade e divulgações de bolsas internacionais.', format:'Listagem cronológica de notícias/editorial.', cadence:'Frequente; itens recentes exibem data e hora.', editals:true, feed:'Não encontrado na verificação inicial.', monitoring:'estruturada', automation:'Boa candidata para monitorar títulos, datas e URLs; curadoria humana preserva contexto e evita duplicações.', reliability:'Oficial primária', verified:checkedAt},
  {id:'ffch', name:'Notícias e editais FFCH', organ:'Faculdade de Filosofia e Ciências Humanas / UFBA', url:'https://ffch.ufba.br/', content:'Editais, resultados, estágios, notícias e atividades da unidade.', format:'Notícias institucionais e documentos anexos.', cadence:'Descentralizada por setores, colegiados e direção; publicações datadas.', editals:false, feed:'Não encontrado na verificação inicial.', monitoring:'semiestruturada', automation:'Monitorar a página institucional ajuda, mas fontes de programas e colegiados também devem ser acompanhadas manualmente.', reliability:'Oficial primária', verified:checkedAt},
  {id:'ppgneim', name:'Resultados de Editais', organ:'PPGNEIM / FFCH / UFBA', url:'https://ppgneim.ffch.ufba.br/pt-br/resultados-editais', content:'Editais e resultados do Programa de Pós-Graduação em Estudos Interdisciplinares sobre Mulheres, Gênero e Feminismo.', format:'Página temática de programa.', cadence:'Por processo seletivo e edital.', editals:true, feed:'Não encontrado na verificação inicial.', monitoring:'descentralizada', automation:'Acompanhamento manual recomendado, complementado por alertas de página.', reliability:'Oficial primária', verified:checkedAt},
  {id:'edufba', name:'Editais', organ:'EDUFBA / UFBA', url:'https://edufba.ufba.br/editais', content:'Chamadas, seleções e estágios da Editora da UFBA.', format:'Página de editais e anexos.', cadence:'Por edital.', editals:true, feed:'Não encontrado na verificação inicial.', monitoring:'semiestruturada', automation:'Monitorar listagem; extrair dados do documento requer conferência humana.', reliability:'Oficial primária', verified:checkedAt},
  {id:'lassos', name:'Eventos LASSOS', organ:'LASSOS / FFCH / UFBA', url:'https://www.lassos.ffch.ufba.br/index.php/category/eventos-lassos/', content:'Seminários, encontros e atividades de laboratório.', format:'Categoria de blog.', cadence:'Variável conforme atividades do laboratório.', editals:false, feed:'Não confirmado na verificação inicial.', monitoring:'descentralizada', automation:'Acompanhamento manual e submissão direta pelo laboratório.', reliability:'Institucional de grupo de pesquisa', verified:checkedAt},
];

export const opportunities = [
  {id:'monitoria-2026-1', title:'Edital PROGRAD/UFBA nº 001/2026 — Programa de Monitoria 2026.1', type:'Monitoria', category:'Ensino', organ:'PROGRAD / UFBA', area:'Multidisciplinar', courses:['Todos os cursos de graduação'], audience:'Estudantes de graduação da UFBA', description:'Edital do Programa de Monitoria divulgado pela Pró-Reitoria de Ensino de Graduação.', requirements:'Consulte o edital oficial.', vacancies:'Não informado pela fonte consultada', scholarship:'Ver edital oficial', value:'Não informado pela fonte consultada', deadline:null, period:'2026.1', modality:'Não informado pela fonte consultada', documents:'Consulte o edital oficial.', apply:'Consulte o edital e os canais da PROGRAD.', contact:'Não informado pela fonte consultada', url:'https://prograd.ufba.br/programa-de-monitoria', edital:'https://prograd.ufba.br/programa-de-monitoria', sourceId:'prograd-monitoria', status:'sem_prazo', verified:checkedAt, provenance:'fonte institucional'},
  {id:'monitoria-ferias-2026', title:'Edital PROGRAD/UFBA nº 002/2026 — Monitoria nos Cursos de Férias', type:'Monitoria', category:'Ensino', organ:'PROGRAD / UFBA', area:'Multidisciplinar', courses:['Todos os cursos de graduação'], audience:'Estudantes de graduação da UFBA', description:'Edital de monitoria para cursos de férias, listado na página institucional da PROGRAD.', requirements:'Consulte o edital oficial.', vacancies:'Não informado pela fonte consultada', scholarship:'Não informado pela fonte consultada', value:'Não informado pela fonte consultada', deadline:null, period:'2026', modality:'Não informado pela fonte consultada', documents:'Consulte o edital oficial.', apply:'Consulte o edital e os canais da PROGRAD.', contact:'Não informado pela fonte consultada', url:'https://prograd.ufba.br/node', edital:'https://prograd.ufba.br/node', sourceId:'prograd-monitoria', status:'sem_prazo', verified:checkedAt, provenance:'fonte institucional'},
  {id:'sri-intercambio-05-2026', title:'Edital nº 05/2026/SRI/UFBA — Programa de Intercâmbio Acadêmico Estudantil Internacional', type:'Mobilidade', category:'Internacionalização', organ:'SRI / UFBA', area:'Multidisciplinar', courses:['Comunidade UFBA'], audience:'Estudantes da UFBA — confirmar critérios no edital', description:'Programa de intercâmbio acadêmico estudantil internacional, com publicação e retificações na página de editais da SRI.', requirements:'Não informado pela fonte consultada; consulte edital e retificações.', vacancies:'Não informado pela fonte consultada', scholarship:'Não informado pela fonte consultada', value:'Não informado pela fonte consultada', deadline:null, period:'2026', modality:'Internacional', documents:'Não informado pela fonte consultada', apply:'Consulte o edital e as retificações no portal da SRI.', contact:'sri@ufba.br', url:'https://sri.ufba.br/pt-br/editais', edital:'https://sri.ufba.br/pt-br/editais', sourceId:'sri', status:'sem_prazo', verified:checkedAt, provenance:'fonte institucional'},
  {id:'proae-promisaes-2026', title:'Edital nº 02/2026 — Bolsas PROMISAES para estudantes PEC-G', type:'Bolsa', category:'Assistência estudantil', organ:'PROAE / UFBA', area:'Permanência estudantil', courses:['Graduação'], audience:'Estudantes do Programa Estudante-Convênio de Graduação (PEC-G)', description:'Seleção de bolsas PROMISAES para estudantes PEC-G, publicada pela PROAE.', requirements:'Ser estudante PEC-G; demais requisitos no edital oficial.', vacancies:'Não informado pela fonte consultada', scholarship:'Sim — PROMISAES', value:'Não informado pela fonte consultada', deadline:null, period:'2026', modality:'Não informado pela fonte consultada', documents:'Consulte o edital oficial.', apply:'Acesse o link da PROAE.', contact:'proae@ufba.br', url:'https://proae.ufba.br/pt-br/edital-no-022026-selecao-de-bolsas-promisaes-para-estudantes-do-programa-estudante-convenio-de-0', edital:'https://proae.ufba.br/pt-br/edital-no-022026-selecao-de-bolsas-promisaes-para-estudantes-do-programa-estudante-convenio-de-0', sourceId:'proae', status:'encerrada', verified:checkedAt, provenance:'fonte institucional'},
  {id:'ffch-estagio-003-2026', title:'Edital 003/2026 — Estágio não obrigatório na FFCH', type:'Estágio', category:'Trabalho e formação', organ:'FFCH / UFBA', area:'Administração universitária', courses:['Cursos de graduação da FFCH'], audience:'Discentes de graduação da FFCH', description:'Processo seletivo simplificado para contratação de estagiários/as para estágio não obrigatório na FFCH.', requirements:'Conforme edital e legislação indicada pela FFCH.', vacancies:'Consulte o edital oficial', scholarship:'Bolsa de estágio — valores no edital', value:'Não informado pela fonte consultada', deadline:null, period:'2026', modality:'Presencial', documents:'Consulte o edital oficial.', apply:'Consulte a página da FFCH e o edital.', contact:'Não informado pela fonte consultada', url:'https://ffch.ufba.br/edital-0032026-processo-seletivo-simplificado-para-contratacao-de-estagiariosas-para-estagio-nao', edital:'https://ffch.ufba.br/edital-0032026-processo-seletivo-simplificado-para-contratacao-de-estagiariosas-para-estagio-nao', sourceId:'ffch', status:'encerrada', verified:checkedAt, provenance:'fonte institucional'},
  {id:'edufba-estagio-01-2026', title:'Edital de seleção de estagiários(as) nº 01/2026 — EDUFBA', type:'Estágio', category:'Trabalho e formação', organ:'EDUFBA / UFBA', area:'Editoração e comunicação', courses:['Graduação UFBA'], audience:'Discentes de graduação da UFBA', description:'Processo seletivo simplificado de estagiários/as para estágio não obrigatório na EDUFBA.', requirements:'Matrícula na graduação UFBA, ter cursado ao menos o 3º semestre, CR igual ou superior a 7 e demais exigências do edital.', vacancies:'Não informado pela fonte consultada', scholarship:'Bolsa de estágio — consultar edital', value:'Não informado pela fonte consultada', deadline:'2026-07-09', period:'2026', modality:'Não informado pela fonte consultada', documents:'Formulário e documentos previstos no edital.', apply:'Conforme edital da EDUFBA.', contact:'Não informado pela fonte consultada', url:'https://edufba.ufba.br/editais/edital-de-selecao-de-estagiariosas-no-012026', edital:'https://edufba.ufba.br/sites/edufba.ufba.br/files/editais/edital_edufba_2026_retificacao_no1_-_selecao_para_estagio_nao_obrigatorio.docx.pdf', sourceId:'edufba', status:'encerrada', verified:checkedAt, provenance:'fonte institucional'},
];

export const posts = [
 {id:'guia-monitoria',section:'Revista',kind:'Guia',title:'Monitoria não é só currículo: por onde começar',excerpt:'Um guia editorial do Nexus para ler editais, conversar com docentes e acompanhar o programa.',demo:true},
 {id:'memoria-corredores',section:'Revista',kind:'Memória',title:'O que os corredores contam sobre São Lázaro',excerpt:'Pauta em construção: arquivo vivo, cartazes, encontros e camadas de tempo.',demo:true},
 {id:'coletivos',section:'Comunidade',kind:'Chamada aberta',title:'Seu coletivo, projeto ou produção pode entrar no mapa',excerpt:'Envie informações para moderação e ajude a ampliar a circulação da comunidade.',demo:true},
 {id:'conquistas',section:'Conquistas',kind:'Convite',title:'Uma conquista também pode virar notícia',excerpt:'Prêmios, publicações, seleções e realizações coletivas: conte ao Nexus.',demo:true},
];

export const events = [
 {id:'event-1',title:'Agenda de São Lázaro: envie atividades abertas',date:'A definir',place:'São Lázaro / online',category:'Chamada comunitária',description:'O MVP abre uma fila de moderação para agenda. Este registro é demonstrativo e não anuncia evento real.',demo:true}
];

export const organizations = [
 {id:'cacs',name:'Centro Acadêmico de Ciências Sociais',sigla:'CACS',course:'Ciências Sociais',instagram:'Não informado',logo:'CACS',currentManagement:null,description:'Organização iniciadora do Nexus. Dados de gestão são administráveis no painel.'},
 {id:'ca-historia',name:'Centro Acadêmico de História',sigla:'CAH',course:'História',instagram:'Não informado',logo:'CAH',currentManagement:null,description:'Espaço preparado para associação de gestão, logos e links.'}
];

export const roles = ['Administrador geral','Editor','Moderador','Redator / Colaborador','Representante de Centro Acadêmico'];
